name: s3-depl

on:
  push:
    branches:
      - develop
env: REACT_APP_SMART_LOOKS_KEY:14abd60ea5105e1d7ddead55a3dca0fa98806d4e
  REACT_APP_S3_URL:https://test-reviewreels-videos.s3.ap-south-1.amazonaws.com/
  REACT_APP_WEB_APP_URL:http://review-reels-frontend-test.s3-website.ap-south-1.amazonaws.com/
  REACT_APP_BACKEND_URL:https://test.reviewreels.app/api/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App

        run: yarn install && yarn build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://review-reels-frontend-test --delete
